name: medical_tour
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  amplitude_flutter: ^3.16.2
  auto_size_text: ^3.0.0
  dropdown_search: ^5.0.6
  flutter:
    sdk: flutter
  flutter_carousel_widget: ^2.3.0
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3
  flutter_web_plugins:
    sdk: flutter  
  google_fonts: ^6.2.1
  responsive_framework: ^1.4.0
  universal_html: ^2.2.4
  url_launcher: ^6.3.0
  video_player: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
